version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: service_account
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8080"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASS: "admin"
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata: